# Lista de Especialidades para Procore
PROCORE_ESPECIALIDADES = [
    "000 - DEM - Demolición",
    "101 - PRE - Caseta para Oficinas, comedor y Cerco perimétrico",
    "102 - PRE - Servicios Higiénicos para Staff y Obreros",
    "103 - PRE - Traslado Vertical y Horizontal",
    "104 - PRE - Equipos y Herramientas",
    "105 - PRE - varios - Obras Preliminares",
    "106 - PRO - Topografía",
    "107 - PRO - Servicios, Energía, Agua y Comunicaciones",
    "108 - PRO - Eliminación de Desmonte y Limpieza permanente",
    "109 - PRO - Eliminación de basura y desmonte con cajas ecológicas",
    "110 - PRO - Control de Calidad",
    "111 - PRO - Seguridad Industrial (EPP y EPC), Patrimonial",
    "112 - PRO - varios - Obras Provisionales",
    "201 - EST - Movimiento de Tierras",
    "202 - EST - Muros Anclados - Estabilización",
    "203 - EST - Concreto Cimentación",
    "204 - EST - Concreto Muros Anclados",
    "205 - EST - Concreto Estacionamientos",
    "206 - EST - Concreto Residencial",
    "207 - EST - Acero Cimentación",
    "208 - EST - Acero Muros Anclados",
    "209 - EST - Acero Estacionamientos",
    "210 - EST - Acero Residencial",
    "211 - EST - Encofrado Cimentación",
    "212 - EST - Encofrado Muros Anclados",
    "213 - EST - Encofrado Estacionamientos",
    "214 - EST - Encofrado Residencial",
    "215 - EST - Sistema de Losas Estacionamientos",
    "216 - EST - Sistema de Losas Residencial",
    "301 - ARQ - Muros de Albañilería",
    "302 - ARQ - Tarrajeo, Revoques y Enlucido",
    "303 - ARQ - Contrapiso y Acabados en Cemento",
    "304 - ARQ - Pisos de enchape cerámico y porcelanato",
    "305 - ARQ - Otros Formatos de Pisos",
    "306 - ARQ - Drywall y Falso Cielo Raso",
    "307 - ARQ - Zócalos",
    "308 - ARQ - Contrazocalos",
    "309 - ARQ - Mármol, Granito, Cuarzo",
    "310 - ARQ - Carpintería de Melamina",
    "311 - ARQ - Carpintería de Madera",
    "312 - ARQ - Carpintería Metálica",
    "313 - ARQ - Vidrios y Cristales",
    "314 - ARQ - Cerrajería",
    "315 - ARQ - Placas y acabados Eléctricas",
    "316 - ARQ - Aparatos Sanitarios y Accesorios",
    "317 - ARQ - Grifería",
    "318 - ARQ - Coberturas",
    "319 - ARQ - Pintura y Recubrimiento",
    "320 - ARQ - Jardinería Interior",
    "321 - ARQ - Jardinería Exterior",
    "322 - ARQ - Otros, Obras Exteriores",
    "323 - ARQ - Papel y Molduras",
    "324 - ARQ - Varios - Arquitectura",
    "401 - IE - IIEE, Voz y Data en Casco",
    "402 - IE - IIEE, Voz y Data en Acabados",
    "403 - IE - Cables Alimentadores",
    "404 - IE - Tableros Eléctricos",
    "501 - IS - IISS redes de agua y desagüe",
    "502 - IS - ACI",
    "601 - IEM - Instalaciones Electromecánicas",
    "701 - IG - Instalaciones de Gas",
    "801 - VAR - Daño a Terceros",
    "802 - VAR - Termino de Obra y Proceso de entrega",
    "803 - VAR - Redes Complementarias Sanitarias",
    "804 - VAR - Redes complementarias Eléctricas - Subestación",
    "901 - ADI - Adicional Comercial",
    "902 - ADI - Adicional de Obra"
]

DEFAULT_PROCORE_TIPO = "Garantía - Llamada de servicio"
DEFAULT_PROCORE_PRIORIDAD = "Urgente"
DEFAULT_PROCORE_ASIGNADO = "Cesar Arrunategui Saavedra"
